{% set name = "python-igraph" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b1e4e3b8ea438f85e17874d0b0836107b437ebe68ae0b3be13d2ad399f45405d

build:
  number: 0
  skip: true  # [win and vc<14]
  script_env:
    - F2C_EXTERNAL_ARITH_HEADER={{ RECIPE_DIR }}/arith_arm64.h  # [arm64]

  run_exports:
    - {{ pin_subpackage("python-igraph", max_pin="x.x") }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - vs2017_{{ target_platform }}  # [win]
    - cmake
    - ninja
    - make  # [not win]
    - pkg-config  # [not win]
  host:
    - glpk
    - libxml2
    - suitesparse
    - arpack   # [not win]
    - gmp  # [not win]
    - mpir  # [win]
    - libblas
    - liblapack
    - python
    - pip
  run:
    - glpk
    - libxml2
    - suitesparse
    - arpack  # [not win]
    - gmp  # [not win]
    - mpir  # [win]
    - texttable >=1.6.2
    - python

test:
  source_files:
    - tests
  imports:
    - igraph
    - igraph.app
    - igraph.drawing
    - igraph.remote
  commands:
    - python -m unittest

about:
  home: https://igraph.org/python/
  license: GPL-2.0-or-later
  license_file:
    - COPYING
    - vendor/source/igraph/ACKNOWLEDGEMENTS.md
  summary: High performance graph data structures and algorithms

extra:
  recipe-maintainers:
    - sodre
    - vtraag
