{% set tests_to_skip = "tests.test_structural.CentralityTests.testAuthorityScore" %}
{% set name = "python-igraph" %}
{% set pypiname = "igraph" %}
{% set version = "1.0.0" %}
{% set igraph_version = "0.10.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: 2414d0be2e4d77ee5357807d100974b40f6082bb1bb71988ec46cfb6728651ee
  patches:
    - 0001-allow-pkgconf.patch

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - pkgconf
  host:
    - python
    - pip
    - setuptools >=64,<72.2.0
    - igraph {{ igraph_version }}
  run:
    - python
    - igraph {{ igraph_version }}
    - texttable >=1.6.2

test:
  source_files:
    - tests
  imports:
    - igraph
    - igraph.app
    - igraph.drawing
    - igraph.remote
  commands:
    - python -m unittest -v

about:
  home: https://igraph.org/python/
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: High performance graph data structures and algorithms
  dev_url: https://github.com/igraph/python-igraph
  doc_url: https://igraph.org/python/#docs

extra:
  recipe-maintainers:
    - sodre
    - vtraag
    - xylar
