{% set name = "python-igraph" %}
{% set version = "0.8.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e1f27622eddeb2bd5fdcbadb41ef048e884790bb050f9627c086dc609d0f1236

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv  # [not win]
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - pkg-config  # [not win]
    - make  # [not win]
    - {{ posix }}autoconf
    - automake  # [not win]
    - {{ posix }}bison
    - {{ posix }}flex
    - {{ posix }}libtool
    - vs2017_{{ target_platform }}  # [win]
    - posix  # [win]
    - m2w64-toolchain  # [win]
    - m2-automake-wrapper  # [win]
  host:
    - gmp  # [not win]
    - icu  # [not win]
    - libiconv  # [not win]
    - libxml2  # [not win]
    - xz  # [not win]
    - zlib  # [not win]
    - texttable >=1.6.2
    - python
    - pip
  run:
    - gmp  # [not win]
    - icu  # [not win]
    - libiconv  # [not win]
    - libxml2  # [not win]
    - xz  # [not win]
    - zlib  # [not win]
    - texttable >=1.6.2
    - pycairo >=1.10,<2
    - python

test:
  source_files:
    - tests
  files:
    - test_cairo.py
    - test_graphml.py  # [not win]
  imports:
    - igraph
    - igraph.app
    - igraph.drawing
    - igraph.remote
  commands:
    - python -m unittest
    - python test_cairo.py
    - python test_graphml.py  # [not win]

about:
  home: https://igraph.org/python/
  license: GPL-2.0-or-later
  license_file:
    - COPYING
    - vendor/source/igraph/ACKNOWLEDGEMENTS.md
  summary: High performance graph data structures and algorithms

extra:
  recipe-maintainers:
    - sodre
    - vtraag
