{% set tests_to_skip = "tests.test_structural.CentralityTests.testAuthorityScore" %}
{% set name = "python-igraph" %}
{% set pypiname = "igraph" %}
{% set version = "0.11.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: d7dc1404567ba3b0ea1bf8b5fa6e101617915c8ad11ea5a9f925a40bf4adad7d

build:
  number: 0
  script_env:
    - F2C_EXTERNAL_ARITH_HEADER={{ RECIPE_DIR }}/arith_arm64.h  # [arm64]

  run_exports:
    - {{ pin_subpackage("python-igraph", max_pin="x.x") }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - make  # [not win]
    - pkg-config  # [not win]
  host:
    - glpk
    - libxml2
    - arpack   # [not win]
    - gmp
    - libblas
    - liblapack
    - python
    - pip
    - setuptools >=64,<72.2.0
    - zlib
  run:
    - glpk
    - libxml2
    - arpack  # [not win]
    - gmp
    - texttable >=1.6.2
    - python

test:
  source_files:
    - tests
  imports:
    - igraph
    - igraph.app
    - igraph.drawing
    - igraph.remote
  commands:
    - python -m unittest -v

about:
  home: https://igraph.org/python/
  license: GPL-2.0-or-later
  license_file:
    - LICENSE
    - vendor/source/igraph/ACKNOWLEDGEMENTS.md
  summary: High performance graph data structures and algorithms
  dev_url: https://github.com/igraph/python-igraph
  doc_url: https://igraph.org/python/#docs

extra:
  recipe-maintainers:
    - sodre
    - vtraag
    - xylar
