{% set tests_to_skip = "tests.test_structural.CentralityTests.testAuthorityScore" %}
{% set name = "python-igraph" %}
{% set pypiname = "igraph" %}
{% set version = "0.11.9" %}
{% set igraph_version = "0.10.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: c57ce44873abcfcfd1d61d7d261e416d352186958e7b5d299cf244efa6757816

build:
  number: 3
  ignore_run_exports_from:
    - igraph
    
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - python
    - pip
    - setuptools >=64,<72.2.0
    - igraph {{ igraph_version }}
    # Windows requires additional libs for pkg-config to work because igraph.pc
    # lists them in Libs
    - arpack  # [win]
    - glpk  # [win]
    - gmp  # [win]
    - libblas  # [win]
    - libiconv  # [win]
    - liblapack  # [win]
    - liblzma-devel  # [win]
    - libxml2-devel  # [win]
  run:
    - python
    - igraph {{ igraph_version }}
    - texttable >=1.6.2

test:
  source_files:
    - tests
  imports:
    - igraph
    - igraph.app
    - igraph.drawing
    - igraph.remote
  commands:
    - python -m unittest -v

about:
  home: https://igraph.org/python/
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: High performance graph data structures and algorithms
  dev_url: https://github.com/igraph/python-igraph
  doc_url: https://igraph.org/python/#docs

extra:
  recipe-maintainers:
    - sodre
    - vtraag
    - xylar
