{% set tests_to_skip = "tests.test_structural.CentralityTests.testAuthorityScore" %}
{% set name = "python-igraph" %}
{% set pypiname = "igraph" %}
{% set version = "0.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: c4053e47156d7685ad48bd72e6ff400d46b09deeebc746b96b5cf9737939fa2d

build:
  number: 1
  skip: true  # [win and vc<14]
  script_env:
    - F2C_EXTERNAL_ARITH_HEADER={{ RECIPE_DIR }}/arith_arm64.h  # [arm64]

  run_exports:
    - {{ pin_subpackage("python-igraph", max_pin="x.x") }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - make  # [not win]
    - pkg-config  # [not win]
  host:
    - glpk
    - libxml2
    - arpack   # [not win]
    - gmp  # [not win]
    - mpir  # [win]
    - libblas
    - liblapack
    - python
    - pip
    - zlib
  run:
    - glpk
    - libxml2
    - arpack  # [not win]
    - gmp  # [not win]
    - mpir  # [win]
    - texttable >=1.6.2
    - python

test:
  source_files:
    - tests
  imports:
    - igraph
    - igraph.app
    - igraph.drawing
    - igraph.remote
  commands:
    # skip some tests that cause intermittent failures
    {% set tests_to_skip = "tests.test_structural.CentralityTests.testAuthorityScore" %}
    {% set tests_to_skip = tests_to_skip + " or tests.test_atlas.GraphAtlasTests.testHubScore" %}
    - python -m unittest -v -k "not ({{ tests_to_skip }})"

about:
  home: https://igraph.org/python/
  license: GPL-2.0-or-later
  license_file:
    - LICENSE
    - vendor/source/igraph/ACKNOWLEDGEMENTS.md
  summary: High performance graph data structures and algorithms
  dev_url: https://github.com/igraph/python-igraph
  doc_url: https://igraph.org/python/#docs

extra:
  recipe-maintainers:
    - sodre
    - vtraag
    - xylar
