{% set name = "python-igraph" %}
{% set version = "0.7.1.post6" %}
{% set sha256 = "a5ea42790a077eadb3d1e8f82edc47516fea4a2b26bbf52bfc148370fe0fe676" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip : true  # [win or py36]

requirements:
  build:
    - python
    - igraph 0.7.1
    - pkg-config
    - setuptools
    - toolchain
    - icu 58.*
  run:
    - python
    - igraph 0.7.1
    - icu 58.*

test:
  imports:
    - igraph
    - igraph.app
    - igraph.drawing
    - igraph.remote
    - igraph.test
    - igraph.vendor

about:
  home: http://pypi.python.org/pypi/python-igraph
  license: GPL
  license_file: COPYING
  summary: 'High performance graph data structures and algorithms'

extra:
  recipe-maintainers:
    - sodre
