appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: aqhb8l89k7JmXPgjXbsfQwasCoaCMV0JrSPFio0fSis9RVSqCwheWOu6f8GB/a/AgePYTcHG6hECa+GveEGGeGf13szhWcOZnOalkWj6aec4TUUbmH8Tu9ElF7xoeYlpA8VYPwVhaE5MPxBEER5LuYQDys8Y/oNmnrEJkCVbks2sbYlll101HvlyVTJvcI9whjE7e16fqxZ4SENl8eiPGvhGgEzyJDHS+9hcI/hkoGhWuabL2fLp8w+SrmRFeihw2yko04yipT+HraeotBuXxyBW04Prg790MaThW8lO004UJBSu9mmYxyjpLUC5r222qlQC1Uz0ec0jhmn3noMx+vUxJdv0itDJP/N3miMy0nJgG3rsN1cvRNqKCJz7viZKDrVg4UkFPzH90RJSdVA8D2kT9NvWDUPBXW/dhiYC8jUYTBG+1fK1ugvFlgseNtNbcfBTkzUqn+/HT8a2WhIoFWLQGnJoPn6FwCnOBm06HAjuvdatdeKmeF7TFBP44R/3J0KXDvEMi9b4RYLiXU9vb5a5liKYkOTc5NAxBZGz4n7BqtCfUKkyWPkmMA5V5eNEFqndD9l8+6s+7lDKnRZ4xauGrfFgO/vYaHz9tFZi0jS8DQIoCcKhfRiSkV6GUeJ1nssh24V6kR8xGa6P+3/sBiF2Cph/3rEwgBf7ySj/szE=}
